In [1]:
import pandas as pd
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize

nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Linzz\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Linzz\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [6]:
df = pd.read_csv("scrape_kompas_clean.csv")
text_column = "title"  # sesuaikan dengan nama kolom

In [15]:
#Memecah teks menjadi kalimat:
text = "Saya belajar NLP. NLP sangat menarik. Saya ingin menjadi NLP Engineer."

sentences = sent_tokenize(text)

for sentence in sentences:
    print(sentence)

Saya belajar NLP.
NLP sangat menarik.
Saya ingin menjadi NLP Engineer.

In [8]:
from nltk.tokenize import word_tokenize

text = "Saya belajar Natural Language Processing."

tokens = word_tokenize(text)

print(tokens)

['Saya', 'belajar', 'Natural', 'Language', 'Processing', '.']

In [9]:
text = "NLP"

characters = list(text)

print(characters)

['N', 'L', 'P']

In [13]:
#Menerapkan word tokenization ke seluruh dataset:
df["tokens"] = df[text_column].astype(str).apply(word_tokenize)

df[[text_column, "tokens"]].head()

,title,tokens
0,Deretan Aktor yang Pernah Perankan Spider-Man,"[Deretan, Aktor, yang, Pernah, Perankan, Spide..."
1,Aktor Ryotaro Shimizu Ditemukan Meninggal Duni...,"[Aktor, Ryotaro, Shimizu, Ditemukan, Meninggal..."
2,"Aktor Marvelous Mrs. Maisel, Josh Grisetti Men...","[Aktor, Marvelous, Mrs., Maisel, ,, Josh, Gris..."
3,"Aktor Bittersweet Destiny, Wang Kai Ditemukan ...","[Aktor, Bittersweet, Destiny, ,, Wang, Kai, Di..."
4,"Aktor Thailand, Jorjay Phumhirun Mendadak Meni...","[Aktor, Thailand, ,, Jorjay, Phumhirun, Mendad..."

In [ ]:
#Menghitung jumlah token per dokumen:
df["jumlah_token"] = df["tokens"].apply(len)
df["jumlah_token"].describe()

count    8926.000000
mean       12.613601
std         2.488254
min         3.000000
25%        11.000000
50%        13.000000
75%        14.000000
max        25.000000
Name: jumlah_token, dtype: float64

In [17]:
#Hitung jumlah kata dengan split sederhana:
df["jumlah_kata"] = df[text_column].astype(str).apply(
    lambda x: len(x.split())
)

#Bandingkan
df[["jumlah_kata", "jumlah_token"]].describe()

       jumlah_kata  jumlah_token
count  8926.000000   8926.000000
mean     11.618866     12.613601
std       2.212300      2.488254
min       3.000000      3.000000
25%      10.000000     11.000000
50%      12.000000     13.000000
75%      13.000000     14.000000
max      23.000000     25.000000

In [18]:
#Amati bagaimana tokenizer menangani berbagai jenis teks:
texts = [
    "Saya suka produk ini.",
    "Bagus banget!!!",
    "Tidak bagus...",
    "Harga Rp50.000.",
    "email@example.com",
    "https://example.com",
    "yg bagus bgt sih",
    "aku udah beli nih kak"
]

for text in texts:
    print("TEXT :", text)
    print("TOKEN:", word_tokenize(text))
    print()

TEXT : Saya suka produk ini.
TOKEN: ['Saya', 'suka', 'produk', 'ini', '.']

TEXT : Bagus banget!!!
TOKEN: ['Bagus', 'banget', '!', '!', '!']

TEXT : Tidak bagus...
TOKEN: ['Tidak', 'bagus', '...']

TEXT : Harga Rp50.000.
TOKEN: ['Harga', 'Rp50.000', '.']

TEXT : email@example.com
TOKEN: ['email', '@', 'example.com']

TEXT : https://example.com
TOKEN: ['https', ':', '//example.com']

TEXT : yg bagus bgt sih
TOKEN: ['yg', 'bagus', 'bgt', 'sih']

TEXT : aku udah beli nih kak
TOKEN: ['aku', 'udah', 'beli', 'nih', 'kak']

In [23]:
import pandas as pd
from nltk.tokenize import word_tokenize

# Teks yang akan diuji
test_texts = [
    "Saya belajar NLP.",
    "Bagus banget!!!",
    "Harga Rp50.000"
]

# Hasil tokenisasi
nltk_hasil = [word_tokenize(t) for t in test_texts]
split_hasil = [t.split() for t in test_texts]

# Tabel perbandingan
tabel = pd.DataFrame({
    "Teks": test_texts,
    "NLTK word_tokenize": nltk_hasil,
    "split()": split_hasil
})

tabel

                Teks        NLTK word_tokenize                split()
0  Saya belajar NLP.   [Saya, belajar, NLP, .]  [Saya, belajar, NLP.]
1    Bagus banget!!!  [Bagus, banget, !, !, !]     [Bagus, banget!!!]
2     Harga Rp50.000         [Harga, Rp50.000]      [Harga, Rp50.000]